"""
generate_pytest.py
------------------
Reads an OpenAPI spec via SpecParser and writes a complete
pytest test suite under tests/generated/.

Run:
    python src/generate_pytest.py specs/petstore.yaml

Output structure:
    tests/generated/
        conftest.py
        test_pet.py
        test_store.py
        test_user.py
"""

from __future__ import annotations

import sys
import os
import re
from pathlib import Path
from collections import defaultdict

# allow running from repo root
sys.path.insert(0, str(Path(__file__).parent))
from spec_parser import SpecParser, TestCase

# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────

INDENT = "    "

# Sample values for fake data by format / type
FAKE_VALUES = {
    "int64":    10,
    "int32":    5,
    "float":    1.5,
    "double":   3.14,
    "string":   '"test_value"',
    "boolean":  "True",
    "email":    '"test@example.com"',
    "date-time": '"2026-05-22T15:45:00Z"',
    "uri":      '"https://example.com/photo.jpg"',
}

WRONG_TYPE_VALUES = {
    "integer": '"not_an_integer"',
    "number":  '"not_a_number"',
    "boolean": '"not_a_bool"',
}


def fake_value(schema: dict) -> str:
    fmt = schema.get("format", "")
    typ = schema.get("type", "string")
    if schema.get("enum"):
        return f'"{schema["enum"][0]}"'
    if fmt in FAKE_VALUES:
        return str(FAKE_VALUES[fmt])
    return str(FAKE_VALUES.get(typ, '"test_value"'))


def build_path(path: str, path_params: list[dict]) -> str:
    """Replace {param} placeholders with fixture references."""
    result = path
    for p in path_params:
        name = p["name"]
        schema = p.get("schema", {})
        val = fake_value(schema)
        result = result.replace(f"{{{name}}}", str(val).strip('"'))
    return result


def build_body(schema: dict, scenario: str, missing_field: str | None = None) -> str:
    """Generate a Python dict literal for the request body."""
    if not schema:
        return "None"
    props = schema.get("properties", {})
    required = schema.get("required", [])
    lines = ["{"]
    for prop, pschema in props.items():
        if scenario == "missing_required" and prop == missing_field:
            continue  # deliberately omit
        val = fake_value(pschema)
        # handle arrays
        if pschema.get("type") == "array":
            item_schema = pschema.get("items", {})
            if item_schema.get("type") == "object":
                val = "[]"
            else:
                val = f'[{fake_value(item_schema)}]'
        lines.append(f'        "{prop}": {val},')
    lines.append("    }")
    return "\n".join(lines)


def build_query_params(query_params: list[dict], scenario: str) -> str:
    if not query_params:
        return "None"
    lines = ["{"]
    for p in query_params:
        name = p["name"]
        schema = p.get("schema", {})
        if scenario == "invalid_enum" and schema.get("enum"):
            val = '"__invalid_enum_value__"'
        else:
            val = fake_value(schema)
        lines.append(f'        "{name}": {val},')
    lines.append("    }")
    return "\n".join(lines)


# ──────────────────────────────────────────────
# Conftest
# ──────────────────────────────────────────────

CONFTEST = '''\
"""
conftest.py  —  shared pytest fixtures
Auto-generated by generate_pytest.py
"""
import pytest
import os

BASE_URL = os.environ.get("API_BASE_URL", "https://petstore3.swagger.io/api/v3")
API_KEY  = os.environ.get("API_KEY", "special-key")


@pytest.fixture(scope="session")
def base_url():
    return BASE_URL


@pytest.fixture(scope="session")
def auth_headers():
    return {"api_key": API_KEY}


@pytest.fixture(scope="session")
def no_auth_headers():
    """Fixture intentionally without auth — used for no_auth tests."""
    return {}
'''

# ──────────────────────────────────────────────
# Per-test function generator
# ──────────────────────────────────────────────

def render_test_function(tc: TestCase) -> str:
    """Return the source code for a single pytest test function."""
    method = tc.method.lower()
    url_path = build_path(tc.path, tc.path_params)
    body = build_body(
        tc.request_body_schema or {},
        tc.scenario,
    )
    params = build_query_params(tc.query_params, tc.scenario)

    # auth fixture
    if tc.scenario == "no_auth":
        auth_arg = "no_auth_headers"
    elif tc.security:
        auth_arg = "auth_headers"
    else:
        auth_arg = "auth_headers"

    expected = tc.expected_status

    lines = [
        f"def {tc.test_name}(base_url, {auth_arg}):",
        f'    """',
        f'    [{tc.tag.upper()}] {tc.summary}',
        f'    Scenario : {tc.scenario}',
        f'    Expected : HTTP {expected}',
        f'    """',
        f'    url = f"{{base_url}}{url_path}"',
    ]

    if body != "None":
        lines.append(f"    payload = {body}")
    if params != "None":
        lines.append(f"    params  = {params}")

    # Build the requests call
    call_args = [f"url", f"headers={auth_arg}"]
    if body != "None":
        call_args.append("json=payload")
    if params != "None":
        call_args.append("params=params")

    lines.append(f"    response = requests.{method}(")
    for i, arg in enumerate(call_args):
        sep = "," if i < len(call_args) - 1 else ""
        lines.append(f"        {arg}{sep}")
    lines.append(f"    )")
    lines.append(f"")
    lines.append(f"    assert response.status_code == {expected}, (")
    lines.append(f'        f"Expected {expected}, got {{response.status_code}}\\n"')
    lines.append(f'        f"Body: {{response.text[:200]}}"')
    lines.append(f"    )")

    # Schema validation on 2xx happy path
    if tc.scenario == "happy_path" and tc.request_body_schema:
        lines += [
            "",
            "    # Basic schema validation",
            "    if response.status_code < 300:",
            "        data = response.json()",
            "        assert isinstance(data, (dict, list)), \\",
            '            "Response should be a JSON object or array"',
        ]

    return "\n".join(f"{INDENT}{line}" if i > 0 else line
                     for i, line in enumerate(lines))


# ──────────────────────────────────────────────
# File generator
# ──────────────────────────────────────────────

def generate_test_file(tag: str, cases: list[TestCase]) -> str:
    """Return the full source of a test_<tag>.py file."""
    header = f'''\
"""
test_{tag}.py
Auto-generated by generate_pytest.py
Source spec : petstore.yaml
Tag         : {tag}
Tests       : {len(cases)}

DO NOT EDIT MANUALLY — re-run generate_pytest.py to regenerate.
"""
import requests
import pytest

'''
    functions = []
    for tc in cases:
        functions.append(render_test_function(tc))
        functions.append("")  # blank line between tests

    return header + "\n".join(functions)


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────

def main(spec_path: str, output_dir: str = "tests/generated") -> None:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    parser = SpecParser(spec_path)
    all_cases = parser.test_cases()

    # Group by tag
    by_tag: dict[str, list[TestCase]] = defaultdict(list)
    for tc in all_cases:
        by_tag[tc.tag].append(tc)

    # Write conftest
    (out / "conftest.py").write_text(CONFTEST)
    (out / "__init__.py").write_text("")

    # Write one file per tag
    for tag, cases in by_tag.items():
        fname = out / f"test_{tag}.py"
        fname.write_text(generate_test_file(tag, cases))

    # Print summary
    print("\n" + "═" * 60)
    print("  PYTEST GENERATOR — Output Summary")
    print("═" * 60)
    print(f"  Spec           : {spec_path}")
    print(f"  Output dir     : {output_dir}/")
    print(f"  Total tests    : {len(all_cases)}")
    print()
    for tag, cases in sorted(by_tag.items()):
        print(f"  test_{tag}.py  →  {len(cases)} tests")
    print()
    s = parser.summary()
    print("  By scenario:")
    for scenario, count in sorted(s["by_scenario"].items()):
        bar = "█" * (count // 2)
        print(f"    {scenario:<20} {count:>3}  {bar}")
    print("═" * 60 + "\n")
    print("  Run with:")
    print(f"    pytest {output_dir}/ -v")
    print(f"    pytest {output_dir}/ -v --tb=short -q")
    print()


if __name__ == "__main__":
    spec  = sys.argv[1] if len(sys.argv) > 1 else "specs/petstore.yaml"
    outd  = sys.argv[2] if len(sys.argv) > 2 else "tests/generated"
    main(spec, outd)
